#!/bin/bash
# ARTWORK
PROJ=iovisor                PROJDB=iovisor                ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 4
PROJ=mininet                PROJDB=mininet                ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 5
PROJ=opennetworkinglab      PROJDB=opennetworkinglab      ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 6
PROJ=opensecuritycontroller PROJDB=opensecuritycontroller ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 7
PROJ=openswitch             PROJDB=openswitch             ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 8
PROJ=p4lang                 PROJDB=p4lang                 ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 9
PROJ=openbmp                PROJDB=openbmp                ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 10
PROJ=tungstenfabric         PROJDB=tungstenfabric         ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 11
PROJ=cord                   PROJDB=cord                   ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 12
PROJ=envoy                  PROJDB=envoy                  ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 13
PROJ=zephyr                 PROJDB=zephyr                 ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 14
PROJ=linux                  PROJDB=linux                  ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 15
PROJ=kubernetes             PROJDB=gha                    ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 16
PROJ=prometheus             PROJDB=prometheus             ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 17
PROJ=opentracing            PROJDB=opentracing            ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 18
PROJ=fluentd                PROJDB=fluentd                ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 19
PROJ=linkerd                PROJDB=linkerd                ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 20
PROJ=grpc                   PROJDB=grpc                   ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 21
PROJ=coredns                PROJDB=coredns                ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 22
PROJ=containerd             PROJDB=containerd             ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 23
PROJ=rkt                    PROJDB=rkt                    ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 24
PROJ=cni                    PROJDB=cni                    ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 25
PROJ=jaeger                 PROJDB=jaeger                 ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 26
PROJ=notary                 PROJDB=notary                 ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 27
PROJ=tuf                    PROJDB=tuf                    ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 28
PROJ=rook                   PROJDB=rook                   ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 29
PROJ=vitess                 PROJDB=vitess                 ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 30
PROJ=nats                   PROJDB=nats                   ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 31
PROJ=opa                    PROJDB=opa                    ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 32
PROJ=spiffe                 PROJDB=spiffe                 ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 33
PROJ=spire                  PROJDB=spire                  ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 34
PROJ=cloudevents            PROJDB=cloudevents            ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 35
PROJ=telepresence           PROJDB=telepresence           ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 36
PROJ=helm                   PROJDB=helm                   ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 37
PROJ=openmetrics            PROJDB=openmetrics            ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 38
PROJ=harbor                 PROJDB=harbor                 ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 39
PROJ=etcd                   PROJDB=etcd                   ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 40
PROJ=tikv                   PROJDB=tikv                   ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 41
PROJ=cortex                 PROJDB=cortex                 ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 42
PROJ=buildpacks             PROJDB=buildpacks             ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 43
PROJ=falco                  PROJDB=falco                  ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 44
PROJ=dragonfly              PROJDB=dragonfly              ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 45
PROJ=virtualkubelet         PROJDB=virtualkubelet         ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 46
PROJ=opencontainers         PROJDB=opencontainers         ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 47
PROJ=cncf                   PROJDB=cncf                   ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 48
PROJ=istio                  PROJDB=istio                  ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 49
PROJ=spinnaker              PROJDB=spinnaker              ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 50
PROJ=knative                PROJDB=knative                ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 51
PROJ=kubeedge               PROJDB=kubeedge               ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 52
PROJ=brigade                PROJDB=brigade                ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 53
PROJ=crio                   PROJDB=crio                   ./kubernetes/apply_manifest.sh ./kubernetes/manifests/devstats-grafana.yaml || exit 54
