---
apiVersion: v1
kind: Pod
metadata:
  name: "devstats-provision-${PROJ}-${TIMESTAMP}"
  labels:
    type: 'provision'
    proj: "${PROJ}"
    name: devstats
spec:
  containers:
  - command:
    - ${CMD}
    args: [${ARGS}]
    resources:
      requests:
        memory: '2Gi'
        cpu: '500m'
      limits:
        memory: '24Gi'
        cpu: '8000m'
    env:
    - name: PROJ
      value: "${PROJ}"
    - name: PROJDB
      value: "${PROJDB}"
    - name: PROJREPO
      value: "${PROJREPO}"
    - name: INIT
      value: "${INIT}"
    - name: ONLYINIT
      value: "${ONLYINIT}"
    - name: SKIPTEMP
      value: "1"
    - name: NOLOCK
      value: "1"
    - name: NOBACKUP
      value: "1"
    - name: SKIPADDALL
      value: "1"
    - name: UDROP
      value: "${UDROP}"
    - name: LDROP
      value: "${LDROP}"
    - name: NOCREATE
      value: "${NOCREATE}"
    - name: TEST_SERVER
      value: "1"
    - name: ONLY
      value: "${PROJ}"
    - name: GETREPOS
      value: "${GETREPOS}"
    - name: WAITBOOT
      value: '30'
    - name: GHA2DB_NCPUS
      value: '${GHA2DB_NCPUS}'
    - name: GHA2DB_USE_ES
      value: '1'
    - name: GHA2DB_USE_ES_RAW
      value: '1'
    - name: GHA2DB_ES_BULK_SIZE
      value: '5000'
    - name: GHA2DB_DEBUG
      value: '${GHA2DB_DEBUG}'
    - name: GHA2DB_CMDDEBUG
      value: '${GHA2DB_CMDDEBUG}'
    - name: GHA2DB_GITHUB_DEBUG
      value: '${GHA2DB_GITHUB_DEBUG}'
    - name: GHA2DB_QOUT
      value: '${GHA2DB_QOUT}'
    - name: GHA2DB_REPOS_DIR
      value: '${GHA2DB_REPOS_DIR}'
    - name: GHA2DB_COMPANY_ACQ_YAML
      value: 'companies.yaml'
    - name: GHA2DB_PROJECTS_YAML
      value: 'k8s/projects.yaml'
    - name: GHA2DB_AFFILIATIONS_JSON
      value: 'github_users.json'
    - name: GHA2DB_COMPUTE_ALL
      value: '${GHA2DB_COMPUTE_ALL}'
    - name: GHA2DB_SKIP_METRICS
      value: '${GHA2DB_SKIP_METRICS}'
    - name: GHA2DB_ONLY_METRICS
      value: '${GHA2DB_ONLY_METRICS}'
    - name: GHA2DB_FORCE_PERIODS
      value: '${GHA2DB_FORCE_PERIODS}'
    - name: GHA2DB_GITHUB_OAUTH
      valueFrom:
        secretKeyRef:
          name: github-oauth
          key: GHA2DB_GITHUB_OAUTH.secret
    - name: ES_PORT
      valueFrom:
        secretKeyRef:
          name: es-db
          key: ES_PORT.secret
    - name: ES_HOST
      valueFrom:
        secretKeyRef:
          name: es-db
          key: ES_HOST.secret
    - name: ES_PROTO
      valueFrom:
        secretKeyRef:
          name: es-db
          key: ES_PROTO.secret
    - name: PG_HOST
      valueFrom:
        secretKeyRef:
          name: pg-db
          key: PG_HOST.secret
    - name: PG_PORT
      valueFrom:
        secretKeyRef:
          name: pg-db
          key: PG_PORT.secret
    - name: PG_PASS
      valueFrom:
        secretKeyRef:
          name: pg-db
          key: PG_PASS.secret
    - name: PG_PASS_RO
      valueFrom:
        secretKeyRef:
          name: pg-db
          key: PG_PASS_RO.secret
    - name: PG_PASS_TEAM
      valueFrom:
        secretKeyRef:
          name: pg-db
          key: PG_PASS_TEAM.secret
    - name: PG_ADMIN_USER
      valueFrom:
        secretKeyRef:
          name: pg-db
          key: PG_ADMIN_USER.secret
    image: lukaszgryglicki/devstats
    imagePullPolicy: Always
    name: 'devstats-provision-${PROJ}-${TIMESTAMP}'
    volumeMounts:
    - name: data
      mountPath: '/root'
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: devstats-git
  restartPolicy: Never
  #nodeSelector:
  #  lfda: devstats
